project 'AudioOdyssey.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AudioOdyssey' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  # Pods for AudioOdyssey
use_frameworks!


  pod 'CountryPickerView'


  target 'AudioOdysseyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AudioOdysseyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
